/**
 * Construction Knowledge Graph — Seed Data
 *
 * Detailed breakdown of every trade in the build process, with sub-items
 * for tasks, materials, inspections, and decision points.
 * Organized by the 8 construction phases from construction-phases.ts.
 */

import type { KnowledgeSeedItem } from '@/types'

export const KNOWLEDGE_SEED_DATA: KnowledgeSeedItem[] = [
  // ═══════════════════════════════════════════════════════════════
  // Phase 1: Pre-Construction
  // ═══════════════════════════════════════════════════════════════
  {
    phase_number: 1,
    trade: 'Site Clearing & Grading',
    item_name: 'Site Clearing & Grading',
    item_type: 'task',
    sort_order: 1,
    description: 'Clear lot, remove trees, grade for drainage and foundation',
    typical_duration_days: 5,
    typical_cost_range: { min: 10000, max: 25000 },
    children: [
      {
        item_name: 'Tree removal & brush clearing',
        item_type: 'task',
        sort_order: 1,
        typical_duration_days: 2,
        description: 'Remove trees in building footprint, chip brush',
      },
      {
        item_name: 'Rough grading',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 2,
        description: 'Grade lot for proper drainage away from foundation',
      },
      {
        item_name: 'Erosion control',
        item_type: 'task',
        sort_order: 3,
        description: 'Install silt fencing and erosion barriers per code',
        inspection_required: true,
        code_references: [{ code: 'IRC', section: 'R401.1', description: 'Soil erosion control during construction' }],
      },
      {
        item_name: 'Choose tree preservation plan',
        item_type: 'decision_point',
        sort_order: 4,
        decision_required: true,
        description: 'Decide which trees to keep and protection measures',
        decision_options: [
          { option: 'Full clear', pros: 'Cheapest, fastest', cons: 'No shade, replanting costs later' },
          { option: 'Selective preservation', pros: 'Keeps mature trees, shade', cons: 'Higher grading cost, root protection needed' },
        ],
      },
    ],
  },
  {
    phase_number: 1,
    trade: 'Well Drilling',
    item_name: 'Well Drilling',
    item_type: 'task',
    sort_order: 2,
    description: 'Drill water well, install casing, pump, and pressure tank',
    typical_duration_days: 5,
    typical_cost_range: { min: 40000, max: 70000 },
    children: [
      {
        item_name: 'Well site selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Determine well location based on geology and setbacks',
        decision_options: [
          { option: 'Geologist-recommended location', pros: 'Best chance of good yield', cons: 'May conflict with building layout' },
          { option: 'Convenience location', pros: 'Shorter run to house', cons: 'May hit rock, lower yield' },
        ],
      },
      {
        item_name: 'Drilling',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 3,
        description: 'Drill to water-bearing formation, install steel casing',
        materials: [
          { name: 'Steel well casing', unit: 'linear foot', specs: '6-inch diameter' },
          { name: 'Well screen', unit: 'each', specs: 'Stainless steel' },
        ],
      },
      {
        item_name: 'Well pump & pressure system',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 1,
        description: 'Install submersible pump, pressure tank, and controls',
        materials: [
          { name: 'Submersible well pump', unit: 'each', specs: '1 HP minimum' },
          { name: 'Pressure tank', unit: 'each', specs: '80+ gallon' },
          { name: 'Well pressure switch', unit: 'each' },
        ],
      },
      {
        item_name: 'Well water test',
        item_type: 'inspection',
        sort_order: 4,
        inspection_required: true,
        description: 'Water quality and flow rate testing',
        code_references: [{ code: 'TCEQ', description: 'Texas water well standards' }],
      },
    ],
  },
  {
    phase_number: 1,
    trade: 'Septic System',
    item_name: 'Septic System',
    item_type: 'task',
    sort_order: 3,
    description: 'Design and install septic system based on soil perc test',
    typical_duration_days: 7,
    typical_cost_range: { min: 15000, max: 40000 },
    children: [
      {
        item_name: 'Soil perc test',
        item_type: 'inspection',
        sort_order: 1,
        inspection_required: true,
        description: 'Percolation test to determine soil absorption rate',
      },
      {
        item_name: 'Septic system design',
        item_type: 'task',
        sort_order: 2,
        description: 'Engineer designs system based on perc results and home size',
      },
      {
        item_name: 'Septic system type',
        item_type: 'decision_point',
        sort_order: 3,
        decision_required: true,
        description: 'Choose septic system type based on soil conditions',
        decision_options: [
          { option: 'Conventional gravity', pros: 'Lowest cost, simplest', cons: 'Requires good perc rate', cost_impact: '$15-25K' },
          { option: 'Aerobic treatment', pros: 'Works in poor soils', cons: 'Higher cost, requires maintenance contract', cost_impact: '$25-40K' },
          { option: 'Drip irrigation', pros: 'Best for difficult sites', cons: 'Most expensive, complex maintenance', cost_impact: '$30-45K' },
        ],
      },
      {
        item_name: 'Septic installation',
        item_type: 'task',
        sort_order: 4,
        typical_duration_days: 4,
        description: 'Install tank, distribution box, and drain field',
      },
      {
        item_name: 'Septic inspection',
        item_type: 'inspection',
        sort_order: 5,
        inspection_required: true,
        description: 'County inspection before backfill',
        code_references: [{ code: 'TCEQ', description: 'On-site sewage facility rules' }],
      },
    ],
  },
  {
    phase_number: 1,
    trade: 'Foundation Engineering',
    item_name: 'Foundation Engineering',
    item_type: 'task',
    sort_order: 4,
    description: 'Geotechnical report and structural foundation design',
    typical_duration_days: 14,
    typical_cost_range: { min: 2000, max: 5000 },
    children: [
      {
        item_name: 'Geotechnical soil report',
        item_type: 'task',
        sort_order: 1,
        typical_duration_days: 7,
        description: 'Soil borings and analysis for foundation design',
      },
      {
        item_name: 'Foundation type selection',
        item_type: 'decision_point',
        sort_order: 2,
        decision_required: true,
        description: 'Select foundation type based on soil report',
        decision_options: [
          { option: 'Post-tension slab', pros: 'Most common in TX, handles expansive clay', cons: 'Cannot cut after pour', cost_impact: '$80-120K' },
          { option: 'Pier and beam', pros: 'Good for slopes, access to plumbing', cons: 'More expensive, requires venting', cost_impact: '$100-150K' },
          { option: 'Rebar slab', pros: 'Can be modified later', cons: 'Less flexible soil handling', cost_impact: '$75-110K' },
        ],
      },
      {
        item_name: 'Structural engineering plans',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 7,
        description: 'Engineer produces foundation plan with beam/cable layout',
      },
    ],
  },
  {
    phase_number: 1,
    trade: 'Civil Engineering',
    item_name: 'Civil Engineering',
    item_type: 'task',
    sort_order: 5,
    description: 'Site plan, drainage, and utility routing design',
    typical_duration_days: 14,
    typical_cost_range: { min: 4000, max: 8000 },
    children: [
      {
        item_name: 'Site plan development',
        item_type: 'task',
        sort_order: 1,
        description: 'Building placement, setbacks, easements, drainage',
      },
      {
        item_name: 'Drainage plan',
        item_type: 'task',
        sort_order: 2,
        description: 'Stormwater management and grading plan',
      },
      {
        item_name: 'Utility routing plan',
        item_type: 'task',
        sort_order: 3,
        description: 'Water, sewer/septic, electric, gas service routing',
      },
    ],
  },
  {
    phase_number: 1,
    trade: 'Survey / Staking',
    item_name: 'Survey / Staking',
    item_type: 'task',
    sort_order: 6,
    description: 'Property survey, boundary markers, and building staking',
    typical_duration_days: 2,
    typical_cost_range: { min: 2000, max: 5000 },
    children: [
      {
        item_name: 'Boundary survey',
        item_type: 'task',
        sort_order: 1,
        description: 'Locate and mark property corners and boundaries',
      },
      {
        item_name: 'Foundation staking',
        item_type: 'task',
        sort_order: 2,
        description: 'Stake building corners and elevation benchmarks',
      },
    ],
  },
  {
    phase_number: 1,
    trade: 'Temporary Utilities',
    item_name: 'Temporary Utilities',
    item_type: 'task',
    sort_order: 7,
    description: 'Temporary power, water, and portable sanitation for site',
    typical_duration_days: 3,
    typical_cost_range: { min: 2000, max: 5000 },
    children: [
      {
        item_name: 'Temporary power pole',
        item_type: 'task',
        sort_order: 1,
        description: 'Install temp power with meter for construction',
        materials: [{ name: 'Temporary power pole and panel', unit: 'each' }],
      },
      {
        item_name: 'Temporary water supply',
        item_type: 'task',
        sort_order: 2,
        description: 'Connect to well or bring water tank for construction',
      },
      {
        item_name: 'Portable toilet',
        item_type: 'task',
        sort_order: 3,
        description: 'Rent portable sanitation unit for construction crew',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 2: Foundation
  // ═══════════════════════════════════════════════════════════════
  {
    phase_number: 2,
    trade: 'Foundation',
    item_name: 'Foundation (Pad Prep + PT Slab)',
    item_type: 'task',
    sort_order: 1,
    description: 'Prepare pad, form, place cables/rebar, pour concrete slab',
    typical_duration_days: 14,
    typical_cost_range: { min: 70000, max: 120000 },
    children: [
      {
        item_name: 'Pad preparation',
        item_type: 'task',
        sort_order: 1,
        typical_duration_days: 3,
        description: 'Fine grade, compact, and prep foundation pad',
        materials: [
          { name: 'Fill dirt / select fill', unit: 'cubic yard', quantity_formula: 'area * depth' },
          { name: 'Vapor barrier', unit: 'sq ft', specs: '10-mil poly sheeting' },
        ],
      },
      {
        item_name: 'Form and beam work',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 3,
        description: 'Set foundation forms and dig beam trenches per engineering',
      },
      {
        item_name: 'Plumbing under-slab rough-in',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 2,
        description: 'Install drain lines and water supply under slab before pour',
        inspection_required: true,
      },
      {
        item_name: 'Under-slab plumbing inspection',
        item_type: 'inspection',
        sort_order: 4,
        inspection_required: true,
        description: 'Pressure test and visual inspection of under-slab plumbing',
        code_references: [{ code: 'IRC', section: 'P2503', description: 'Plumbing inspection before concealment' }],
      },
      {
        item_name: 'Post-tension cable / rebar placement',
        item_type: 'task',
        sort_order: 5,
        typical_duration_days: 2,
        description: 'Install PT cables or rebar per structural engineering plan',
        materials: [
          { name: 'Post-tension cables', unit: 'each', specs: 'Per engineering plan' },
          { name: 'Rebar', unit: 'ton', specs: '#4 and #5 bars' },
        ],
      },
      {
        item_name: 'Pre-pour inspection',
        item_type: 'inspection',
        sort_order: 6,
        inspection_required: true,
        description: 'City/county inspection of forms, steel, and plumbing before pour',
        code_references: [{ code: 'IRC', section: 'R506', description: 'Concrete slab-on-ground floors' }],
      },
      {
        item_name: 'Concrete pour',
        item_type: 'task',
        sort_order: 7,
        typical_duration_days: 1,
        description: 'Pour foundation concrete, finish, and begin curing',
        materials: [
          { name: 'Ready-mix concrete', unit: 'cubic yard', specs: '3500 PSI minimum' },
        ],
      },
      {
        item_name: 'Post-tension stressing',
        item_type: 'task',
        sort_order: 8,
        typical_duration_days: 1,
        description: 'Stress PT cables after concrete reaches required strength (3-5 days)',
      },
      {
        item_name: 'Foundation survey',
        item_type: 'inspection',
        sort_order: 9,
        inspection_required: true,
        description: 'Survey foundation for dimensional accuracy before framing',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 3: Framing & Structure
  // ═══════════════════════════════════════════════════════════════
  {
    phase_number: 3,
    trade: 'Framing',
    item_name: 'Framing (Lumber + Labor)',
    item_type: 'task',
    sort_order: 1,
    description: 'Frame walls, floors, and roof structure',
    typical_duration_days: 30,
    typical_cost_range: { min: 100000, max: 160000 },
    children: [
      {
        item_name: 'Lumber delivery and layout',
        item_type: 'task',
        sort_order: 1,
        typical_duration_days: 1,
        description: 'Receive lumber package and layout on slab',
        materials: [
          { name: 'Framing lumber package', unit: 'board feet', specs: '2x4, 2x6, 2x8, 2x12' },
          { name: 'Engineered beams (LVL/PSL)', unit: 'each', specs: 'Per structural plan' },
          { name: 'Plywood/OSB sheathing', unit: 'sheet', specs: '7/16" or 1/2"' },
        ],
      },
      {
        item_name: 'Wall framing',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 10,
        description: 'Frame exterior and interior walls, stand and brace',
      },
      {
        item_name: 'Second floor framing',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 5,
        description: 'Frame second floor joists and subfloor if applicable',
      },
      {
        item_name: 'Roof framing',
        item_type: 'task',
        sort_order: 4,
        typical_duration_days: 7,
        description: 'Set trusses or cut rafters, install ridge, sheath roof',
      },
      {
        item_name: 'Wall sheathing',
        item_type: 'task',
        sort_order: 5,
        typical_duration_days: 3,
        description: 'Install wall sheathing (OSB/plywood) for structural bracing',
      },
      {
        item_name: 'Framing inspection',
        item_type: 'inspection',
        sort_order: 6,
        inspection_required: true,
        description: 'Structural framing inspection before concealment',
        code_references: [{ code: 'IRC', section: 'R301', description: 'Structural design criteria' }],
      },
    ],
  },
  {
    phase_number: 3,
    trade: 'Trusses',
    item_name: 'Trusses / Engineered Lumber',
    item_type: 'task',
    sort_order: 2,
    description: 'Engineered roof trusses and floor trusses',
    typical_duration_days: 3,
    typical_cost_range: { min: 25000, max: 50000 },
    children: [
      {
        item_name: 'Truss engineering and fabrication',
        item_type: 'task',
        sort_order: 1,
        description: 'Engineer designs trusses, manufacturer fabricates',
        typical_duration_days: 14,
      },
      {
        item_name: 'Truss delivery and setting',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 2,
        description: 'Deliver trusses to site, crane set onto walls',
      },
    ],
  },
  {
    phase_number: 3,
    trade: 'Roofing',
    item_name: 'Roofing',
    item_type: 'task',
    sort_order: 3,
    description: 'Install underlayment, flashing, and roofing material',
    typical_duration_days: 5,
    typical_cost_range: { min: 20000, max: 45000 },
    children: [
      {
        item_name: 'Roofing material selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose roofing material type and color',
        decision_options: [
          { option: '30-year architectural shingles', pros: 'Most affordable, easy to repair', cons: 'Shorter lifespan', cost_impact: '$20-30K' },
          { option: 'Standing seam metal', pros: '50+ year life, energy efficient', cons: 'Higher upfront cost', cost_impact: '$35-55K' },
          { option: 'Concrete/clay tile', pros: 'Very long life, fire resistant', cons: 'Heavy (structural implications), expensive', cost_impact: '$40-60K' },
        ],
      },
      {
        item_name: 'Roof underlayment',
        item_type: 'task',
        sort_order: 2,
        description: 'Install synthetic underlayment and ice/water shield',
        materials: [
          { name: 'Synthetic underlayment', unit: 'roll', specs: 'Self-adhering at valleys/eaves' },
          { name: 'Ice and water shield', unit: 'roll', specs: 'At eaves, valleys, penetrations' },
        ],
      },
      {
        item_name: 'Flashing installation',
        item_type: 'task',
        sort_order: 3,
        description: 'Install step, valley, and penetration flashings',
      },
      {
        item_name: 'Roofing material install',
        item_type: 'task',
        sort_order: 4,
        typical_duration_days: 3,
        description: 'Install chosen roofing material',
      },
    ],
  },
  {
    phase_number: 3,
    trade: 'WRB & Flashings',
    item_name: 'WRB & Flashings',
    item_type: 'task',
    sort_order: 4,
    description: 'Weather-resistive barrier and window/door flashings',
    typical_duration_days: 3,
    typical_cost_range: { min: 5000, max: 12000 },
    children: [
      {
        item_name: 'House wrap / WRB installation',
        item_type: 'task',
        sort_order: 1,
        description: 'Install weather-resistive barrier over wall sheathing',
        materials: [
          { name: 'House wrap (Tyvek/similar)', unit: 'roll', specs: 'Lapped and taped per manufacturer' },
        ],
      },
      {
        item_name: 'Window and door flashing',
        item_type: 'task',
        sort_order: 2,
        description: 'Flash window and door rough openings before installation',
        materials: [
          { name: 'Flashing tape', unit: 'roll', specs: 'Self-adhering flexible flashing' },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 4: Rough-Ins (MEP)
  // ═══════════════════════════════════════════════════════════════
  {
    phase_number: 4,
    trade: 'HVAC',
    item_name: 'HVAC Rough-In',
    item_type: 'task',
    sort_order: 1,
    description: 'Install ductwork, refrigerant lines, and drain lines',
    typical_duration_days: 7,
    typical_cost_range: { min: 35000, max: 60000 },
    children: [
      {
        item_name: 'HVAC system design',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Select HVAC system type and zoning',
        decision_options: [
          { option: 'Central air (single zone)', pros: 'Lowest cost', cons: 'Uneven temps in large homes', cost_impact: '$25-35K' },
          { option: 'Multi-zone ducted', pros: 'Zone control, comfort', cons: 'More ductwork, higher cost', cost_impact: '$40-55K' },
          { option: 'Mini-split (ductless)', pros: 'Most efficient, zone control', cons: 'Interior wall units, highest cost', cost_impact: '$50-70K' },
          { option: 'Geothermal', pros: 'Lowest operating cost', cons: 'Very high upfront cost', cost_impact: '$60-90K' },
        ],
      },
      {
        item_name: 'Ductwork installation',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 4,
        description: 'Install supply and return ductwork per Manual D design',
        materials: [
          { name: 'Sheet metal ductwork', unit: 'linear foot' },
          { name: 'Flex duct', unit: 'linear foot', specs: 'R-8 insulated' },
          { name: 'Duct boots and registers', unit: 'each' },
        ],
      },
      {
        item_name: 'Refrigerant line sets',
        item_type: 'task',
        sort_order: 3,
        description: 'Run copper refrigerant lines from units to condenser',
      },
      {
        item_name: 'HVAC rough-in inspection',
        item_type: 'inspection',
        sort_order: 4,
        inspection_required: true,
        description: 'Inspect ductwork installation and sealing',
        code_references: [{ code: 'IRC', section: 'M1601', description: 'Duct construction and installation' }],
      },
    ],
  },
  {
    phase_number: 4,
    trade: 'Plumbing Rough',
    item_name: 'Plumbing Rough-In',
    item_type: 'task',
    sort_order: 2,
    description: 'Install supply and DWV (drain-waste-vent) piping',
    typical_duration_days: 7,
    typical_cost_range: { min: 25000, max: 50000 },
    children: [
      {
        item_name: 'Supply line installation',
        item_type: 'task',
        sort_order: 1,
        description: 'Run hot and cold water supply lines to all fixtures',
        materials: [
          { name: 'PEX supply pipe', unit: 'linear foot', specs: '3/4" and 1/2"' },
          { name: 'PEX fittings and manifold', unit: 'each' },
        ],
      },
      {
        item_name: 'DWV piping',
        item_type: 'task',
        sort_order: 2,
        description: 'Install drain, waste, and vent piping',
        materials: [
          { name: 'PVC DWV pipe', unit: 'linear foot', specs: '2", 3", 4"' },
          { name: 'PVC fittings', unit: 'each' },
          { name: 'Vent flashings', unit: 'each' },
        ],
      },
      {
        item_name: 'Water heater rough-in',
        item_type: 'task',
        sort_order: 3,
        description: 'Set water heater location, run supply/drain/gas/vent',
      },
      {
        item_name: 'Water heater type',
        item_type: 'decision_point',
        sort_order: 4,
        decision_required: true,
        description: 'Choose water heating system',
        decision_options: [
          { option: 'Tankless gas', pros: 'Unlimited hot water, space saving', cons: 'Higher upfront cost, gas line needed', cost_impact: '$2-4K per unit' },
          { option: 'Tank gas (50-80 gal)', pros: 'Proven, lower upfront', cons: 'Standby heat loss, takes space', cost_impact: '$1-2K' },
          { option: 'Heat pump water heater', pros: 'Most efficient, uses electricity', cons: 'Needs warm air space, slower recovery', cost_impact: '$2-3K' },
        ],
      },
      {
        item_name: 'Plumbing rough-in inspection',
        item_type: 'inspection',
        sort_order: 5,
        inspection_required: true,
        description: 'Pressure test supply lines, inspect DWV for proper slope/venting',
        code_references: [{ code: 'IRC', section: 'P2503', description: 'Plumbing rough-in inspection' }],
      },
    ],
  },
  {
    phase_number: 4,
    trade: 'Electrical',
    item_name: 'Electrical Rough-In',
    item_type: 'task',
    sort_order: 3,
    description: 'Install wiring, junction boxes, panels, and low-voltage',
    typical_duration_days: 10,
    typical_cost_range: { min: 30000, max: 55000 },
    children: [
      {
        item_name: 'Main panel installation',
        item_type: 'task',
        sort_order: 1,
        description: 'Install 200A+ main panel and meter base',
        materials: [
          { name: 'Main breaker panel', unit: 'each', specs: '200A minimum, 40+ spaces' },
          { name: 'Meter base', unit: 'each' },
        ],
      },
      {
        item_name: 'Branch circuit wiring',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 5,
        description: 'Run Romex to all outlets, switches, and fixtures',
        materials: [
          { name: 'Romex 14/2 (15A circuits)', unit: 'roll' },
          { name: 'Romex 12/2 (20A circuits)', unit: 'roll' },
          { name: 'Romex 10/2 (30A circuits)', unit: 'roll' },
          { name: 'Junction boxes', unit: 'each' },
          { name: 'Outlet/switch boxes', unit: 'each' },
        ],
      },
      {
        item_name: 'GFCI and AFCI protection',
        item_type: 'task',
        sort_order: 3,
        description: 'Install GFCI outlets in wet areas, AFCI breakers per code',
        code_references: [
          { code: 'NEC', section: '210.8', description: 'GFCI protection required locations' },
          { code: 'NEC', section: '210.12', description: 'AFCI protection in dwelling units' },
        ],
      },
      {
        item_name: 'Dedicated circuits',
        item_type: 'task',
        sort_order: 4,
        description: 'Wire dedicated circuits for HVAC, range, dryer, disposal, dishwasher',
        materials: [
          { name: 'Romex 6/3 (range/oven)', unit: 'roll' },
          { name: 'Romex 10/3 (dryer)', unit: 'roll' },
        ],
      },
      {
        item_name: 'Low-voltage rough-in',
        item_type: 'task',
        sort_order: 5,
        description: 'Run Cat6, coax, speaker wire, security wiring',
        materials: [
          { name: 'Cat6 ethernet cable', unit: 'box', specs: '1000ft boxes' },
          { name: 'RG6 coax cable', unit: 'box' },
          { name: 'Speaker wire', unit: 'roll', specs: '16-gauge, 2-conductor' },
        ],
      },
      {
        item_name: 'EV charger pre-wire',
        item_type: 'decision_point',
        sort_order: 6,
        decision_required: true,
        description: 'Pre-wire for electric vehicle charger in garage',
        decision_options: [
          { option: 'Install now (Level 2, 50A)', pros: 'Ready to use, cheapest during construction', cons: 'May not need yet', cost_impact: '$500-1500' },
          { option: 'Pre-wire conduit only', pros: 'Easy to add later, minimal cost now', cons: 'Still need electrician later', cost_impact: '$200-400' },
          { option: 'Skip', pros: 'No cost now', cons: 'Expensive retrofit later if needed', cost_impact: '$0 now, $2-4K later' },
        ],
      },
      {
        item_name: 'Electrical rough-in inspection',
        item_type: 'inspection',
        sort_order: 7,
        inspection_required: true,
        description: 'Inspect wiring, boxes, panel, grounding before concealment',
        code_references: [{ code: 'NEC', section: '210', description: 'Branch circuits and outlets' }],
      },
    ],
  },
  {
    phase_number: 4,
    trade: 'ERV & IAQ',
    item_name: 'ERV / Indoor Air Quality',
    item_type: 'task',
    sort_order: 4,
    description: 'Energy recovery ventilator and indoor air quality systems',
    typical_duration_days: 2,
    typical_cost_range: { min: 5000, max: 12000 },
    children: [
      {
        item_name: 'ERV unit installation',
        item_type: 'task',
        sort_order: 1,
        description: 'Install ERV unit and duct to fresh air intakes/exhausts',
        materials: [
          { name: 'ERV unit', unit: 'each', specs: '200+ CFM' },
          { name: 'ERV ductwork', unit: 'linear foot' },
        ],
      },
      {
        item_name: 'Whole-house ventilation',
        item_type: 'decision_point',
        sort_order: 2,
        decision_required: true,
        description: 'Choose ventilation strategy for tight building envelope',
        decision_options: [
          { option: 'ERV (energy recovery ventilator)', pros: 'Recovers energy, balanced ventilation', cons: 'Higher cost, maintenance', cost_impact: '$5-12K' },
          { option: 'HRV (heat recovery ventilator)', pros: 'Good for heating-dominant climates', cons: 'Less effective in humid TX climate', cost_impact: '$4-10K' },
          { option: 'Exhaust-only', pros: 'Cheapest', cons: 'No energy recovery, negative pressure', cost_impact: '$500-1K' },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 5: Building Envelope
  // ═══════════════════════════════════════════════════════════════
  {
    phase_number: 5,
    trade: 'Windows & Doors',
    item_name: 'Windows & Doors',
    item_type: 'task',
    sort_order: 1,
    description: 'Install exterior windows and doors',
    typical_duration_days: 5,
    typical_cost_range: { min: 50000, max: 90000 },
    children: [
      {
        item_name: 'Window selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose window brand, frame material, and glazing',
        decision_options: [
          { option: 'Vinyl (Milgard, Simonton)', pros: 'Lowest cost, low maintenance', cons: 'Limited colors, less robust', cost_impact: '$30-50K' },
          { option: 'Fiberglass (Marvin, Pella)', pros: 'Durable, paintable, good performance', cons: 'Higher cost', cost_impact: '$50-80K' },
          { option: 'Wood-clad (Andersen, Marvin)', pros: 'Best aesthetics, wood interior', cons: 'Most expensive, wood maintenance', cost_impact: '$60-100K' },
        ],
      },
      {
        item_name: 'Window installation',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 3,
        description: 'Install and flash all windows',
      },
      {
        item_name: 'Exterior door installation',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 2,
        description: 'Install entry doors, patio doors, garage entry door',
      },
    ],
  },
  {
    phase_number: 5,
    trade: 'Siding',
    item_name: 'Exterior Siding / Cladding',
    item_type: 'task',
    sort_order: 2,
    description: 'Install exterior wall cladding material',
    typical_duration_days: 14,
    typical_cost_range: { min: 30000, max: 65000 },
    children: [
      {
        item_name: 'Siding material selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose exterior cladding material',
        decision_options: [
          { option: 'Fiber cement (Hardie)', pros: 'Durable, fire resistant, many styles', cons: 'Heavy, professional install', cost_impact: '$25-45K' },
          { option: 'Stucco (traditional)', pros: 'Classic look, good for French Country', cons: 'Can crack, moisture issues', cost_impact: '$30-50K' },
          { option: 'Engineered wood (LP SmartSide)', pros: 'Lightweight, easy install', cons: 'Less fire resistant than cement', cost_impact: '$20-35K' },
          { option: 'Brick veneer', pros: 'Very durable, classic TX look', cons: 'Most expensive, heavy', cost_impact: '$45-80K' },
        ],
      },
      {
        item_name: 'Siding installation',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 10,
        description: 'Install exterior cladding material with proper trim',
      },
    ],
  },
  {
    phase_number: 5,
    trade: 'Insulation',
    item_name: 'Insulation',
    item_type: 'task',
    sort_order: 3,
    description: 'Insulate walls, attic, and rim joist areas',
    typical_duration_days: 3,
    typical_cost_range: { min: 12000, max: 25000 },
    children: [
      {
        item_name: 'Insulation type selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose insulation type and R-value targets',
        decision_options: [
          { option: 'Open-cell spray foam', pros: 'Great air sealing, fills gaps', cons: 'Not moisture barrier, absorbs water', cost_impact: '$12-20K' },
          { option: 'Closed-cell spray foam', pros: 'Highest R-value/inch, moisture barrier', cons: 'Most expensive', cost_impact: '$18-30K' },
          { option: 'Blown fiberglass (walls) + spray foam (rim)', pros: 'Good balance of cost and performance', cons: 'Less air sealing than spray foam', cost_impact: '$10-16K' },
          { option: 'Batt fiberglass', pros: 'Lowest cost', cons: 'Gaps, settling, poor air sealing', cost_impact: '$6-10K' },
        ],
      },
      {
        item_name: 'Wall insulation install',
        item_type: 'task',
        sort_order: 2,
        description: 'Insulate exterior walls to code-minimum R-value',
        code_references: [{ code: 'IECC', section: 'R402.1', description: 'Insulation R-value requirements by climate zone' }],
      },
      {
        item_name: 'Attic insulation install',
        item_type: 'task',
        sort_order: 3,
        description: 'Insulate attic floor or roofline per design',
      },
      {
        item_name: 'Insulation inspection',
        item_type: 'inspection',
        sort_order: 4,
        inspection_required: true,
        description: 'Inspect insulation installation and R-values before drywall',
        code_references: [{ code: 'IECC', section: 'R402', description: 'Building thermal envelope' }],
      },
    ],
  },
  {
    phase_number: 5,
    trade: 'Stone & Masonry',
    item_name: 'Stone / Masonry Accents',
    item_type: 'task',
    sort_order: 4,
    description: 'Install exterior stone or masonry accent features',
    typical_duration_days: 10,
    typical_cost_range: { min: 15000, max: 40000 },
    children: [
      {
        item_name: 'Stone/brick selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose stone or masonry type for accents',
        decision_options: [
          { option: 'Natural stone veneer', pros: 'Authentic look, unique', cons: 'Heavy, expensive, slower install', cost_impact: '$25-45K' },
          { option: 'Manufactured stone', pros: 'Lighter, consistent, easier install', cons: 'Less authentic', cost_impact: '$15-30K' },
          { option: 'Thin brick veneer', pros: 'Classic look, moderate cost', cons: 'Limited styles', cost_impact: '$18-35K' },
        ],
      },
      {
        item_name: 'Stone/masonry installation',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 8,
        description: 'Install stone or masonry with proper drainage and weep system',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 6: Interior Finishes
  // ═══════════════════════════════════════════════════════════════
  {
    phase_number: 6,
    trade: 'Drywall',
    item_name: 'Drywall',
    item_type: 'task',
    sort_order: 1,
    description: 'Hang, tape, mud, and finish drywall throughout',
    typical_duration_days: 14,
    typical_cost_range: { min: 25000, max: 50000 },
    children: [
      {
        item_name: 'Drywall hanging',
        item_type: 'task',
        sort_order: 1,
        typical_duration_days: 5,
        description: 'Hang drywall sheets on walls and ceilings',
        materials: [
          { name: 'Drywall sheets', unit: 'sheet', specs: '1/2" standard, 5/8" fire-rated where required' },
          { name: 'Drywall screws', unit: 'box' },
        ],
      },
      {
        item_name: 'Drywall texture selection',
        item_type: 'decision_point',
        sort_order: 2,
        decision_required: true,
        description: 'Choose wall and ceiling texture finish',
        decision_options: [
          { option: 'Smooth (Level 5)', pros: 'Modern, clean look', cons: 'Most expensive, shows imperfections', cost_impact: '+$3-5K' },
          { option: 'Light knockdown', pros: 'Hides imperfections, easy to repair', cons: 'Harder to clean', cost_impact: 'Standard' },
          { option: 'Orange peel', pros: 'Classic, easy to apply', cons: 'Dated look', cost_impact: 'Standard' },
        ],
      },
      {
        item_name: 'Taping and finishing',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 7,
        description: 'Tape joints, apply mud coats, sand, and texture',
      },
    ],
  },
  {
    phase_number: 6,
    trade: 'Doors & Trim',
    item_name: 'Interior Doors & Trim',
    item_type: 'task',
    sort_order: 2,
    description: 'Install interior doors, casings, baseboards, and crown',
    typical_duration_days: 10,
    typical_cost_range: { min: 18000, max: 35000 },
    children: [
      {
        item_name: 'Interior door installation',
        item_type: 'task',
        sort_order: 1,
        typical_duration_days: 4,
        description: 'Hang pre-hung interior doors',
        materials: [
          { name: 'Interior doors (pre-hung)', unit: 'each', specs: 'Solid core recommended for bedrooms' },
        ],
      },
      {
        item_name: 'Baseboard and casing installation',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 4,
        description: 'Install baseboards, door casings, and window casings',
        materials: [
          { name: 'Baseboard molding', unit: 'linear foot' },
          { name: 'Door/window casing', unit: 'linear foot' },
        ],
      },
      {
        item_name: 'Crown molding',
        item_type: 'decision_point',
        sort_order: 3,
        decision_required: true,
        description: 'Choose crown molding style and which rooms',
        decision_options: [
          { option: 'Full crown throughout', pros: 'Elegant, consistent', cons: 'Expensive, especially with high ceilings', cost_impact: '+$5-10K' },
          { option: 'Crown in main areas only', pros: 'Good balance', cons: 'Transition points', cost_impact: '+$3-6K' },
          { option: 'No crown, clean modern look', pros: 'Cost savings, modern aesthetic', cons: 'May feel unfinished in French Country style', cost_impact: '$0' },
        ],
      },
    ],
  },
  {
    phase_number: 6,
    trade: 'Painting',
    item_name: 'Painting',
    item_type: 'task',
    sort_order: 3,
    description: 'Prime and paint interior walls, trim, doors, and ceilings',
    typical_duration_days: 10,
    typical_cost_range: { min: 18000, max: 35000 },
    children: [
      {
        item_name: 'Paint color selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose interior paint colors for each room/area',
      },
      {
        item_name: 'Priming',
        item_type: 'task',
        sort_order: 2,
        description: 'Prime all drywall, trim, and doors',
      },
      {
        item_name: 'Finish painting',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 7,
        description: 'Apply finish coats to walls, ceilings, trim, and doors',
      },
    ],
  },
  {
    phase_number: 6,
    trade: 'Cabinetry',
    item_name: 'Cabinetry',
    item_type: 'task',
    sort_order: 4,
    description: 'Install kitchen, bathroom, laundry, and built-in cabinetry',
    typical_duration_days: 5,
    typical_cost_range: { min: 40000, max: 80000 },
    children: [
      {
        item_name: 'Cabinet selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose cabinet style, material, and manufacturer',
        decision_options: [
          { option: 'Stock cabinets (Home Depot/Lowes)', pros: 'Lowest cost, fast delivery', cons: 'Limited options, lower quality', cost_impact: '$20-35K' },
          { option: 'Semi-custom (KraftMaid, Diamond)', pros: 'Good quality, many options', cons: 'Longer lead time', cost_impact: '$35-60K' },
          { option: 'Full custom (local cabinet shop)', pros: 'Exact fit, any design', cons: 'Most expensive, longest lead time', cost_impact: '$50-100K+' },
        ],
      },
      {
        item_name: 'Kitchen cabinet installation',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 3,
        description: 'Install upper and lower kitchen cabinets',
      },
      {
        item_name: 'Bathroom & utility cabinet install',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 2,
        description: 'Install vanities, linen cabinets, and laundry cabinetry',
      },
    ],
  },
  {
    phase_number: 6,
    trade: 'Countertops',
    item_name: 'Countertops',
    item_type: 'task',
    sort_order: 5,
    description: 'Template, fabricate, and install countertops',
    typical_duration_days: 7,
    typical_cost_range: { min: 30000, max: 60000 },
    children: [
      {
        item_name: 'Countertop material selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose countertop material for kitchen and baths',
        decision_options: [
          { option: 'Quartz (Caesarstone, Cambria)', pros: 'Durable, no sealing, consistent', cons: 'Heat sensitive, manufactured look', cost_impact: '$50-100/sq ft' },
          { option: 'Granite', pros: 'Natural beauty, heat resistant', cons: 'Needs sealing, can stain', cost_impact: '$40-80/sq ft' },
          { option: 'Quartzite', pros: 'Hardest natural stone, beautiful', cons: 'Most expensive, needs sealing', cost_impact: '$70-150/sq ft' },
          { option: 'Marble', pros: 'Elegant, classic', cons: 'Stains easily, etches with acid', cost_impact: '$60-120/sq ft' },
        ],
      },
      {
        item_name: 'Templating',
        item_type: 'task',
        sort_order: 2,
        description: 'Laser template countertops after cabinets are set',
      },
      {
        item_name: 'Fabrication and installation',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 1,
        description: 'Fabricate and install countertop slabs',
      },
    ],
  },
  {
    phase_number: 6,
    trade: 'Tile',
    item_name: 'Tile & Stone',
    item_type: 'task',
    sort_order: 6,
    description: 'Install tile in bathrooms, kitchen backsplash, fireplace',
    typical_duration_days: 14,
    typical_cost_range: { min: 20000, max: 45000 },
    children: [
      {
        item_name: 'Tile selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose tile materials for floors, showers, and backsplash',
      },
      {
        item_name: 'Shower waterproofing',
        item_type: 'task',
        sort_order: 2,
        description: 'Install waterproof membrane in shower areas (Kerdi, RedGard)',
        inspection_required: true,
        materials: [
          { name: 'Waterproof membrane', unit: 'sq ft', specs: 'Schluter Kerdi or liquid-applied' },
        ],
      },
      {
        item_name: 'Floor tile installation',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 5,
        description: 'Install floor tiles in bathrooms, laundry, entry',
      },
      {
        item_name: 'Shower/tub surround tile',
        item_type: 'task',
        sort_order: 4,
        typical_duration_days: 5,
        description: 'Install wall tile in shower and tub surrounds',
      },
      {
        item_name: 'Kitchen backsplash',
        item_type: 'task',
        sort_order: 5,
        typical_duration_days: 2,
        description: 'Install tile backsplash behind kitchen counters',
      },
    ],
  },
  {
    phase_number: 6,
    trade: 'Flooring',
    item_name: 'Flooring',
    item_type: 'task',
    sort_order: 7,
    description: 'Install flooring throughout (hardwood, LVP, carpet)',
    typical_duration_days: 10,
    typical_cost_range: { min: 80000, max: 130000 },
    children: [
      {
        item_name: 'Flooring material selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose flooring type for each area of the home',
        decision_options: [
          { option: 'Hardwood (engineered)', pros: 'Real wood look, stable, can refinish', cons: 'Expensive, water sensitive', cost_impact: '$8-15/sq ft installed' },
          { option: 'Luxury vinyl plank (LVP)', pros: 'Waterproof, durable, affordable', cons: 'Not real wood, can dent', cost_impact: '$5-10/sq ft installed' },
          { option: 'Solid hardwood', pros: 'Premium feel, long life', cons: 'Most expensive, moisture sensitive, long acclimation', cost_impact: '$10-20/sq ft installed' },
        ],
      },
      {
        item_name: 'Hardwood/LVP installation',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 7,
        description: 'Install primary flooring throughout main areas',
      },
      {
        item_name: 'Carpet installation',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 2,
        description: 'Install carpet in bedrooms and closets',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 7: MEP Finishes
  // ═══════════════════════════════════════════════════════════════
  {
    phase_number: 7,
    trade: 'Plumbing Fixtures',
    item_name: 'Plumbing Fixtures',
    item_type: 'task',
    sort_order: 1,
    description: 'Install all plumbing fixtures, faucets, and connections',
    typical_duration_days: 5,
    typical_cost_range: { min: 15000, max: 35000 },
    children: [
      {
        item_name: 'Fixture selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose plumbing fixtures for all bathrooms and kitchen',
      },
      {
        item_name: 'Toilet installation',
        item_type: 'task',
        sort_order: 2,
        description: 'Install toilets in all bathrooms',
      },
      {
        item_name: 'Faucet and sink installation',
        item_type: 'task',
        sort_order: 3,
        description: 'Install kitchen and bath faucets and sinks',
      },
      {
        item_name: 'Shower fixture installation',
        item_type: 'task',
        sort_order: 4,
        description: 'Install shower heads, valves, and bath fixtures',
      },
      {
        item_name: 'Plumbing final inspection',
        item_type: 'inspection',
        sort_order: 5,
        inspection_required: true,
        description: 'Final plumbing inspection — all fixtures operational',
        code_references: [{ code: 'IRC', section: 'P2503', description: 'Final plumbing inspection' }],
      },
    ],
  },
  {
    phase_number: 7,
    trade: 'Lighting Fixtures',
    item_name: 'Lighting Fixtures',
    item_type: 'task',
    sort_order: 2,
    description: 'Install all interior lighting fixtures, switches, and dimmers',
    typical_duration_days: 3,
    typical_cost_range: { min: 10000, max: 25000 },
    children: [
      {
        item_name: 'Lighting fixture selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose lighting fixtures for each room',
      },
      {
        item_name: 'Fixture hanging/mounting',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 2,
        description: 'Install chandeliers, pendants, can lights, sconces',
      },
      {
        item_name: 'Switch/dimmer/outlet installation',
        item_type: 'task',
        sort_order: 3,
        description: 'Install switches, dimmers, outlets, and cover plates',
      },
      {
        item_name: 'Electrical final inspection',
        item_type: 'inspection',
        sort_order: 4,
        inspection_required: true,
        description: 'Final electrical inspection — all fixtures, outlets, panels',
        code_references: [{ code: 'NEC', section: '210', description: 'Final electrical inspection' }],
      },
    ],
  },
  {
    phase_number: 7,
    trade: 'Appliances',
    item_name: 'Appliances',
    item_type: 'task',
    sort_order: 3,
    description: 'Deliver and install all kitchen and laundry appliances',
    typical_duration_days: 2,
    typical_cost_range: { min: 15000, max: 200000 },
    children: [
      {
        item_name: 'Appliance selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose kitchen and laundry appliance package',
      },
      {
        item_name: 'Appliance delivery and installation',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 1,
        description: 'Receive and install all appliances, connect utilities',
      },
      {
        item_name: 'HVAC final — equipment startup',
        item_type: 'task',
        sort_order: 3,
        description: 'Commission HVAC systems, test heating/cooling, set thermostats',
      },
      {
        item_name: 'Mechanical final inspection',
        item_type: 'inspection',
        sort_order: 4,
        inspection_required: true,
        description: 'Final HVAC/mechanical inspection — equipment operational',
        code_references: [{ code: 'IRC', section: 'M1401', description: 'Mechanical equipment inspection' }],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 8: Exterior & Site
  // ═══════════════════════════════════════════════════════════════
  {
    phase_number: 8,
    trade: 'Driveway',
    item_name: 'Driveway / Flatwork',
    item_type: 'task',
    sort_order: 1,
    description: 'Pour concrete driveway, sidewalks, and patios',
    typical_duration_days: 5,
    typical_cost_range: { min: 15000, max: 30000 },
    children: [
      {
        item_name: 'Driveway material selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose driveway and flatwork material',
        decision_options: [
          { option: 'Standard concrete', pros: 'Durable, affordable', cons: 'Basic look', cost_impact: '$8-12/sq ft' },
          { option: 'Stamped/stained concrete', pros: 'Decorative, good look', cons: 'More expensive, maintenance', cost_impact: '$12-18/sq ft' },
          { option: 'Pavers', pros: 'Best aesthetics, repairable', cons: 'Most expensive, weed maintenance', cost_impact: '$15-25/sq ft' },
        ],
      },
      {
        item_name: 'Concrete pour — driveway',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 2,
        description: 'Form and pour driveway concrete',
      },
      {
        item_name: 'Sidewalks and patios',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 2,
        description: 'Pour sidewalks, patios, and other flatwork',
      },
    ],
  },
  {
    phase_number: 8,
    trade: 'Garage Doors',
    item_name: 'Garage Doors',
    item_type: 'task',
    sort_order: 2,
    description: 'Install garage doors and openers',
    typical_duration_days: 1,
    typical_cost_range: { min: 5000, max: 12000 },
    children: [
      {
        item_name: 'Garage door selection',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose garage door style, material, and opener',
        decision_options: [
          { option: 'Steel insulated', pros: 'Affordable, durable, low maintenance', cons: 'Can dent', cost_impact: '$1.5-3K per door' },
          { option: 'Wood carriage style', pros: 'Beautiful, French Country aesthetic', cons: 'Expensive, maintenance', cost_impact: '$3-6K per door' },
          { option: 'Aluminum/glass modern', pros: 'Light, modern look', cons: 'Less insulation, doesn\'t fit style', cost_impact: '$2-4K per door' },
        ],
      },
      {
        item_name: 'Garage door installation',
        item_type: 'task',
        sort_order: 2,
        description: 'Install doors, tracks, springs, and smart openers',
      },
    ],
  },
  {
    phase_number: 8,
    trade: 'Exterior Lighting',
    item_name: 'Exterior Lighting',
    item_type: 'task',
    sort_order: 3,
    description: 'Install landscape, path, accent, and security lighting',
    typical_duration_days: 3,
    typical_cost_range: { min: 8000, max: 20000 },
    children: [
      {
        item_name: 'Exterior lighting design',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Design exterior lighting layout for safety and aesthetics',
      },
      {
        item_name: 'Fixture installation',
        item_type: 'task',
        sort_order: 2,
        description: 'Install wall sconces, path lights, uplights, and flood lights',
      },
    ],
  },
  {
    phase_number: 8,
    trade: 'Pool',
    item_name: 'Pool',
    item_type: 'task',
    sort_order: 4,
    description: 'Pool design, excavation, plumbing, finishing, and equipment',
    typical_duration_days: 45,
    typical_cost_range: { min: 60000, max: 120000 },
    children: [
      {
        item_name: 'Pool design and type',
        item_type: 'decision_point',
        sort_order: 1,
        decision_required: true,
        description: 'Choose pool type, size, and features',
        decision_options: [
          { option: 'Gunite/shotcrete', pros: 'Any shape/size, most durable', cons: 'Most expensive, longest build time', cost_impact: '$70-120K' },
          { option: 'Fiberglass', pros: 'Fast install, low maintenance', cons: 'Limited shapes/sizes', cost_impact: '$50-80K' },
        ],
      },
      {
        item_name: 'Pool excavation',
        item_type: 'task',
        sort_order: 2,
        typical_duration_days: 3,
        description: 'Dig pool hole and haul away dirt',
      },
      {
        item_name: 'Pool plumbing and electrical',
        item_type: 'task',
        sort_order: 3,
        typical_duration_days: 5,
        description: 'Install pool plumbing, equipment pad, and electrical',
      },
      {
        item_name: 'Pool shell construction',
        item_type: 'task',
        sort_order: 4,
        typical_duration_days: 5,
        description: 'Rebar, gunite/shotcrete, or set fiberglass shell',
      },
      {
        item_name: 'Pool finish and fill',
        item_type: 'task',
        sort_order: 5,
        typical_duration_days: 5,
        description: 'Apply interior finish (plaster, pebble, tile), fill, startup',
      },
      {
        item_name: 'Pool barrier/fence inspection',
        item_type: 'inspection',
        sort_order: 6,
        inspection_required: true,
        description: 'Verify pool barrier compliance before filling',
        code_references: [{ code: 'IRC', section: 'R326', description: 'Swimming pool barrier requirements' }],
      },
    ],
  },
]
