import { NextRequest } from 'next/server'
import { classifyEmail } from '@/lib/email-classifier'
import { db } from '@/lib/database'
import { getProject, updateProjectStatus } from '@/lib/project-service'
import { getAuthenticatedGmailService } from '@/lib/gmail-auth'
import { successResponse, errorResponse } from '@/lib/api-utils'
import { AuthenticationError } from '@/lib/errors'
import { extractEmailAddress, extractSenderName } from '@/lib/ui-helpers'
import { createEmailSyncNotification } from '@/lib/notification-service'
import type { EmailRecord } from '@/types'

// Process emails in batches to avoid overwhelming the AI API
const AI_BATCH_SIZE = 3

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams
    const forceRefresh = searchParams.get('refresh') === 'true'

    // First, try to get emails from database
    const storedEmails = await db.getRecentEmails(7)

    // If we have stored emails and not forcing refresh, return them
    if (storedEmails.length > 0 && !forceRefresh) {
      console.log(`Returning ${storedEmails.length} stored emails from database`)

      // Convert database format to frontend format
      const emailsWithSummaries = storedEmails.map(email => ({
        id: email.message_id,
        threadId: email.thread_id || '',
        subject: email.subject,
        from: email.sender_name ? `${email.sender_name} <${email.sender_email}>` : email.sender_email,
        date: email.received_date,
        body: email.body_text || '',
        snippet: email.body_text?.substring(0, 200) || '',
        aiSummary: email.ai_summary
      }))

      // Return latest unified project status
      const project = await getProject()
      const status = project ? await db.getLatestProjectStatus(project.id) : null

      return successResponse({
        emails: emailsWithSummaries,
        status,
        count: emailsWithSummaries.length,
        lastFetched: new Date().toISOString(),
        source: 'database' as const
      })
    }

    // Fall back to live Gmail API if no stored emails or forcing refresh
    console.log('Fetching emails from Gmail API...')

    const gmailService = await getAuthenticatedGmailService()
    if (!gmailService) {
      throw new AuthenticationError()
    }

    // Build search query dynamically from project contacts
    const project = await getProject()
    const searchQuery = project
      ? await db.buildEmailSearchQuery(project.id, 7)
      : '(label:inbox OR in:sent OR is:important) newer_than:7d'
    const emails = await gmailService.getEmails(searchQuery)

    // Classify emails using rule-based system (no AI API calls)
    const emailsWithInsights: Array<{
      id: string; threadId: string; subject: string; from: string;
      date: string; body: string; snippet: string;
      attachments?: Array<{ filename: string; mimeType: string; attachmentId: string; size: number }>;
      classification: ReturnType<typeof classifyEmail>;
      aiSummary: string;
    }> = []

    for (const email of emails) {
      const senderEmail = extractEmailAddress(email.from)
      const classification = classifyEmail(senderEmail, email.subject, email.body.substring(0, 500))

      emailsWithInsights.push({
        ...email,
        classification,
        aiSummary: '', // Summaries generated by Claude Code, not inline
      })
    }

    // Persist fetched emails to the database so the assistant and cron can access them
    if (project && emailsWithInsights.length > 0) {
      const emailAccount = await db.getEmailAccount(process.env.GMAIL_USER_EMAIL || '')
      const emailsToStore: EmailRecord[] = []

      for (const email of emailsWithInsights) {
        const exists = await db.emailExists(email.id)
        if (exists) continue

        emailsToStore.push({
          project_id: project.id,
          email_account_id: emailAccount?.id,
          message_id: email.id,
          thread_id: email.threadId,
          sender_email: extractEmailAddress(email.from),
          sender_name: extractSenderName(email.from),
          subject: email.subject,
          body_text: email.body,
          received_date: email.date,
          ai_summary: email.aiSummary || undefined,
          has_attachments: (email.attachments?.length ?? 0) > 0,
          urgency_level: 'medium',
          category: email.classification.category,
        })
      }

      if (emailsToStore.length > 0) {
        console.log(`Storing ${emailsToStore.length} emails to database...`)
        const storedRecords = await db.storeEmails(emailsToStore)

        // Store attachment metadata for emails that have them
        for (const email of emailsWithInsights) {
          if (email.attachments && email.attachments.length > 0) {
            const stored = storedRecords.find(r => r.message_id === email.id)
            if (stored?.id) {
              await db.storeEmailAttachments(stored.id, email.attachments)
            }
          }
        }

        // Notify about new emails
        await createEmailSyncNotification(project.id, emailsToStore.length)
      }

      // Always regenerate status on manual refresh (even if no new emails)
      console.log('Triggering project status update...')
      await updateProjectStatus(project.id)
    }

    // Return latest unified project status
    const status = project ? await db.getLatestProjectStatus(project.id) : null

    return successResponse({
      emails: emailsWithInsights,
      status,
      count: emailsWithInsights.length,
      lastFetched: new Date().toISOString(),
      source: 'gmail-api' as const
    })
  } catch (error) {
    return errorResponse(error, 'Failed to fetch emails')
  }
}
