#!/usr/bin/env node

/**
 * Reorganize Documents Using AI Classifications
 *
 * Uses the AI_CLASSIFICATIONS.json file generated by ai-document-classifier.js
 * to accurately organize documents based on their actual content.
 *
 * Usage:
 *   node scripts/reorganize-with-ai.js --dry-run     # Preview
 *   node scripts/reorganize-with-ai.js --execute     # Execute
 */

const fs = require('fs-extra');
const path = require('path');
const chalk = require('chalk');

// Default paths - auto-detect WSL vs Windows
const getDefaultPaths = () => {
  if (process.platform === 'win32') {
    return {
      source: 'C:\\Users\\danie\\Dropbox\\Properties\\Austin, TX\\Liberty Hill\\708 Purple Salvia Cove',
      target: 'C:\\Users\\danie\\Dropbox\\Properties\\Austin, TX\\Liberty Hill\\708 Purple Salvia Cove_ORGANIZED'
    };
  } else {
    return {
      source: '/mnt/c/Users/danie/Dropbox/Properties/Austin, TX/Liberty Hill/708 Purple Salvia Cove',
      target: '/mnt/c/Users/danie/Dropbox/Properties/Austin, TX/Liberty Hill/708 Purple Salvia Cove_ORGANIZED'
    };
  }
};

const defaultPaths = getDefaultPaths();

// Folder structure that AI classifier uses
const FOLDER_STRUCTURE = {
  '00_PROJECT_ESSENTIALS': {
    description: 'Quick access to most critical documents',
    subdirs: ['Current_Plans', 'Current_Budget', 'Active_Contracts']
  },
  '01_PLANS_AND_ENGINEERING': {
    description: 'Architectural plans, engineering drawings, and surveys',
    subdirs: ['Architectural/CURRENT', 'Architectural/ARCHIVE',
              'Engineering/Foundation', 'Engineering/Structural', 'Engineering/Roofing',
              'Engineering/Site_Work', 'Survey']
  },
  '02_PERMITS_AND_REGULATORY': {
    description: 'Building permits, HOA submissions, and utility connections',
    subdirs: ['Building_Permits', 'HOA/Submissions', 'HOA/Rules_and_Restrictions',
              'Utilities/Electric', 'Utilities/Water_Well', 'Utilities/Septic', 'Utilities']
  },
  '03_BIDS_AND_ESTIMATES': {
    description: 'All vendor bids organized by category',
    subdirs: ['BY_CATEGORY/Appliances', 'BY_CATEGORY/Electrical', 'BY_CATEGORY/Engineering',
              'BY_CATEGORY/Excavation_and_Septic', 'BY_CATEGORY/Flooring', 'BY_CATEGORY/Garage_Doors',
              'BY_CATEGORY/Plumbing_Fixtures', 'BY_CATEGORY/Pool', 'BY_CATEGORY/Stone_Fabrication',
              'BY_CATEGORY/Well_Drilling', 'BY_CATEGORY/Windows_and_Doors', 'BY_CATEGORY',
              'SELECTED_BIDS', 'REJECTED_BIDS']
  },
  '04_CONTRACTS_AND_AGREEMENTS': {
    description: 'Executed contracts and legal agreements',
    subdirs: ['Land_Purchase', 'Vendors', 'Financial/Construction_Loan', 'Financial/Appraisals']
  },
  '05_EXPENSES_AND_RECEIPTS': {
    description: 'Paid receipts organized by vendor and month',
    subdirs: ['BY_VENDOR', 'BY_MONTH']
  },
  '06_DESIGN_AND_SPECIFICATIONS': {
    description: 'Design inspiration and final selections',
    subdirs: ['Design_Inspiration/Bathrooms', 'Design_Inspiration/Countertops',
              'Design_Inspiration/Exterior', 'Design_Inspiration/Fireplace',
              'Design_Inspiration/Garage_Doors', 'Design_Inspiration',
              'Final_Selections']
  },
  '07_SITE_PROGRESS': {
    description: 'Construction progress photos and logs',
    subdirs: ['Photos', 'Daily_Logs', 'Inspections']
  },
  '08_COMMUNICATIONS': {
    description: 'Email threads and vendor correspondence',
    subdirs: ['Email_Threads', 'Vendor_Correspondence', 'Design_Consultations']
  },
  '09_REFERENCE_AND_TEMPLATES': {
    description: 'UBuildIt process documents and templates',
    subdirs: ['UBuildIt_Process', 'Construction_Management', 'Vendor_Resources']
  },
  '10_ARCHIVE': {
    description: 'Old versions and superseded documents',
    subdirs: ['Old_Versions', 'Duplicates', 'Financial_Documents', 'Uncategorized']
  }
};

/**
 * Load AI classifications
 */
async function loadClassifications(classificationsPath) {
  if (!await fs.pathExists(classificationsPath)) {
    throw new Error(`Classifications file not found: ${classificationsPath}\nRun ai-document-classifier.js first!`);
  }

  const classifications = await fs.readJson(classificationsPath);
  console.log(chalk.green(`✓ Loaded ${classifications.length} classifications\n`));

  return classifications;
}

/**
 * Create folder structure
 */
async function createFolderStructure(targetRoot) {
  console.log(chalk.yellow('Creating folder structure...'));

  for (const [folder, config] of Object.entries(FOLDER_STRUCTURE)) {
    const folderPath = path.join(targetRoot, folder);
    await fs.ensureDir(folderPath);

    // Create subdirectories
    for (const subdir of config.subdirs) {
      const subdirPath = path.join(folderPath, subdir);
      await fs.ensureDir(subdirPath);
    }

    // Create INDEX.md
    const indexPath = path.join(folderPath, 'INDEX.md');
    let indexContent = `# ${folder.replace(/_/g, ' ')}\n\n`;
    indexContent += `${config.description}\n\n`;
    indexContent += `*Auto-generated by AI-powered reorganization script*\n`;
    await fs.writeFile(indexPath, indexContent);
  }

  console.log(chalk.green('✓ Folder structure created\n'));
}

/**
 * Generate reorganization plan from AI classifications
 */
function generatePlan(classifications, sourceRoot) {
  console.log(chalk.yellow('Generating reorganization plan from AI classifications...'));

  const plan = {
    copy: [],
    skip: [],
    stats: {
      byCategory: {},
      byConfidence: { high: 0, medium: 0, low: 0 }
    }
  };

  classifications.forEach(item => {
    // Count by category
    if (!plan.stats.byCategory[item.category]) {
      plan.stats.byCategory[item.category] = 0;
    }
    plan.stats.byCategory[item.category]++;

    // Count by confidence
    if (item.confidence >= 0.9) plan.stats.byConfidence.high++;
    else if (item.confidence >= 0.7) plan.stats.byConfidence.medium++;
    else plan.stats.byConfidence.low++;

    // Add to copy list
    plan.copy.push({
      from: item.file,
      to: path.join(item.targetFolder, item.filename),
      category: item.category,
      confidence: item.confidence,
      reasoning: item.reasoning
    });
  });

  console.log(chalk.green('✓ Plan generated\n'));

  return plan;
}

/**
 * Write detailed plan report
 */
async function writePlanReport(plan, outputPath) {
  let report = '# AI-Based Reorganization Plan\n\n';
  report += `Generated: ${new Date().toISOString()}\n\n`;

  // Summary
  report += '## Summary\n\n';
  report += `- Total files to copy: ${plan.copy.length}\n`;
  report += `- High confidence (≥90%): ${plan.stats.byConfidence.high}\n`;
  report += `- Medium confidence (70-90%): ${plan.stats.byConfidence.medium}\n`;
  report += `- Low confidence (<70%): ${plan.stats.byConfidence.low}\n\n`;

  // By category
  report += '## Files by Category\n\n';
  report += '| Category | Count |\n';
  report += '|----------|-------|\n';
  Object.entries(plan.stats.byCategory).sort((a, b) => b[1] - a[1]).forEach(([cat, count]) => {
    report += `| ${cat} | ${count} |\n`;
  });

  // Detailed file list (first 100)
  report += '\n## Detailed File Moves (First 100)\n\n';

  plan.copy.slice(0, 100).forEach((item, index) => {
    const confEmoji = item.confidence >= 0.9 ? '✅' : item.confidence >= 0.7 ? '⚠️' : '❌';
    report += `${index + 1}. ${confEmoji} **${path.basename(item.from)}**\n`;
    report += `   - **Category:** ${item.category}\n`;
    report += `   - **From:** \`${item.from}\`\n`;
    report += `   - **To:** \`${item.to}\`\n`;
    report += `   - **Confidence:** ${(item.confidence * 100).toFixed(0)}%\n`;
    report += `   - **Reasoning:** ${item.reasoning}\n\n`;
  });

  if (plan.copy.length > 100) {
    report += `\n*...and ${plan.copy.length - 100} more files*\n\n`;
  }

  report += '\n---\n';
  report += '**Review this plan carefully before executing!**\n';

  await fs.writeFile(outputPath, report);
  console.log(chalk.green(`✓ Plan saved to: ${outputPath}\n`));
}

/**
 * Execute the reorganization plan
 */
async function executePlan(plan, sourceRoot, targetRoot) {
  console.log(chalk.yellow('Executing reorganization...\n'));

  let successCount = 0;
  let errorCount = 0;

  for (let i = 0; i < plan.copy.length; i++) {
    const item = plan.copy[i];
    const sourcePath = path.join(sourceRoot, item.from);
    const targetPath = path.join(targetRoot, item.to);

    try {
      // Ensure target directory exists
      await fs.ensureDir(path.dirname(targetPath));

      // Copy file
      await fs.copy(sourcePath, targetPath, { overwrite: true });

      successCount++;

      if ((i + 1) % 50 === 0) {
        console.log(chalk.gray(`  Copied ${i + 1}/${plan.copy.length} files...`));
      }
    } catch (error) {
      console.error(chalk.red(`✗ Error copying ${item.from}:`), error.message);
      errorCount++;
    }
  }

  console.log(chalk.green(`\n✓ Copied ${successCount} files successfully`));
  if (errorCount > 0) {
    console.log(chalk.red(`✗ ${errorCount} files failed to copy\n`));
  }

  // Generate log
  const logPath = path.join(targetRoot, 'AI_REORGANIZATION_LOG.md');
  let log = '# AI-Based Reorganization Log\n\n';
  log += `Executed: ${new Date().toISOString()}\n\n`;
  log += `Files copied: ${successCount}\n`;
  log += `Errors: ${errorCount}\n\n`;

  log += '## All Operations\n\n';
  plan.copy.forEach((item, i) => {
    log += `${i + 1}. [${item.category}] ${item.from} → ${item.to}\n`;
  });

  await fs.writeFile(logPath, log);
  console.log(chalk.green(`✓ Log saved to: ${logPath}\n`));
}

/**
 * Main execution
 */
async function main() {
  console.log(chalk.bold.cyan('\n🤖 AI-Based Document Reorganization\n'));

  // Parse arguments
  const args = process.argv.slice(2);
  let sourceDir = defaultPaths.source;
  let targetDir = defaultPaths.target;
  let classificationsPath = path.join(process.cwd(), 'AI_CLASSIFICATIONS.json');
  let dryRun = true;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--source' && args[i + 1]) {
      sourceDir = args[i + 1];
      i++;
    } else if (args[i] === '--target' && args[i + 1]) {
      targetDir = args[i + 1];
      i++;
    } else if (args[i] === '--classifications' && args[i + 1]) {
      classificationsPath = args[i + 1];
      i++;
    } else if (args[i] === '--dry-run') {
      dryRun = true;
    } else if (args[i] === '--execute') {
      dryRun = false;
    }
  }

  // Verify source exists
  if (!await fs.pathExists(sourceDir)) {
    console.error(chalk.red(`✗ Source directory not found: ${sourceDir}`));
    process.exit(1);
  }

  console.log(chalk.blue(`Source: ${sourceDir}`));
  console.log(chalk.blue(`Target: ${targetDir}`));
  console.log(chalk.blue(`Mode: ${dryRun ? 'DRY RUN (no changes)' : 'EXECUTE (will create files)'}\n`));

  // Step 1: Load AI classifications
  console.log(chalk.yellow('Step 1: Loading AI classifications...'));
  const classifications = await loadClassifications(classificationsPath);

  // Step 2: Create folder structure
  await createFolderStructure(targetDir);

  // Step 3: Generate plan
  const plan = generatePlan(classifications, sourceDir);

  // Step 4: Write plan report
  const planPath = path.join(process.cwd(), 'AI_REORGANIZATION_PLAN.md');
  await writePlanReport(plan, planPath);

  if (dryRun) {
    // Dry run complete
    console.log(chalk.bold.green('\n✓ Dry Run Complete!\n'));
    console.log(chalk.cyan('Summary:'));
    console.log(chalk.white(`  Files to organize: ${plan.copy.length}`));
    console.log(chalk.white(`  High confidence: ${plan.stats.byConfidence.high}`));
    console.log(chalk.white(`  Medium confidence: ${plan.stats.byConfidence.medium}`));
    console.log(chalk.white(`  Low confidence: ${plan.stats.byConfidence.low}\n`));

    console.log(chalk.cyan('Next steps:'));
    console.log(chalk.white('  1. Review AI_REORGANIZATION_PLAN.md'));
    console.log(chalk.white('  2. Edit AI_CLASSIFICATIONS.json if corrections needed'));
    console.log(chalk.white('  3. Run with --execute to perform reorganization\n'));

    if (plan.stats.byConfidence.low > 0) {
      console.log(chalk.yellow(`⚠️  ${plan.stats.byConfidence.low} files have low confidence (<70%)`));
      console.log(chalk.white('   Review AI_CLASSIFICATION_REVIEW.md for details\n'));
    }
  } else {
    // Execute reorganization
    console.log(chalk.yellow('EXECUTE MODE - Performing reorganization\n'));

    await executePlan(plan, sourceDir, targetDir);

    console.log(chalk.bold.green('\n✓ Reorganization Complete!\n'));
    console.log(chalk.cyan('Summary:'));
    console.log(chalk.white(`  Files organized: ${plan.copy.length}`));
    console.log(chalk.white(`  Target directory: ${targetDir}`));
    console.log(chalk.white(`  Original preserved: Yes\n`));

    console.log(chalk.cyan('Next steps:'));
    console.log(chalk.white('  1. Review the organized folder structure'));
    console.log(chalk.white('  2. Run: npm run docs:extract (populate database)'));
    console.log(chalk.white('  3. Run: npm run docs:packages (create shareable packages)\n'));
  }
}

// Run the script
if (require.main === module) {
  main().catch(error => {
    console.error(chalk.red('\n✗ Error:'), error);
    process.exit(1);
  });
}

module.exports = { generatePlan, loadClassifications };
