// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgvckbmwanmngryskari.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndmNrYm13YW5tbmdyeXNrYXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzkzNzQsImV4cCI6MjA2ODQ1NTM3NH0.tAJbXlBrK526_YpgxgVUnniez9lmx3p7wATCgvYAcSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});